% Lower One-sided VSI EWMA X-bar Chart for Gamma %
% Zero State %
% Search for lambda, hL, K1 and K2 %

function [lam, hL, K1, K2, ATS1, SDTS1, ASI1, ATS0, SDTS0, ASI0] = OptAtsLowerVsiEwmaXbarGam(n, hS, delta, tau0, a_shape, b_scale)

% Initial guess
x0 = [0.1, 1.5, 0.65, 2.1];

% Bounds
lb = [0.05, 1.02, 0.6, 1.51];
ub = [0.95, 1.65, 1.5, 4.00];

options = optimoptions('fmincon', ...
    'Algorithm', 'interior-point', ...
    'TolFun', 1e-10, ...
    'TolX', 1e-10, ...
    'TolCon', 1e-10, ...
    'MaxIterations', 500, ...
    'Display', 'off', ...
    'OutputFcn', @(x,optimValues,state) ...
        OutFunLowerVsiEwmaXbarGam( ...
        x, optimValues, state, ...
        n, hS, delta, tau0, a_shape, b_scale));

x = fmincon(@(x) ...
    ObjLowerVsiEwmaXbarGam(x, n, hS, delta, a_shape, b_scale), ...
    x0, [], [], [], [], lb, ub, ...
    @(x) ConLowerVsiEwmaXbarGam(x, n, hS, tau0, a_shape, b_scale), ...
    options);

lam = x(1);
hL  = x(2);
K1  = x(3);
K2  = x(4);

% Final performance
[ATS1, SDTS1, ASI1] = TsLowerVsiEwmaXbarGam(n, hL, hS, lam, K1, K2, delta, a_shape, b_scale);

[ATS0, SDTS0, ASI0] = TsLowerVsiEwmaXbarGam(n, hL, hS, lam, K1, K2, 0, a_shape, b_scale);

fprintf(['lam = %6.4f  hL = %6.4f  K1 = %6.4f  K2 = %6.4f  ', ...
         'ATS0 = %6.2f  ASI0 = %6.2f ATS1 = %6.2f SDTS1 = %6.2f \n'], ...
         lam, hL, K1, K2, ATS0, ASI0, ATS1, SDTS1);
end
