% Lower One-sided VSI EWMA X-bar Chart for Gamma %
% Steady State %
% Search for lambda, hL, K1 and K2 %

function [lam, hL, K1, K2, EAATS1, AATS0, ASI0] = OptAtsLowerVsiEwmaXbarGamEAATS(n, hS, deltamin, deltamax, tau0, a_shape, b_scale)

% Initial guess
x0 = [0.1, 1.2, 0.7, 2.4];

% Bounds
lb = [0.05, 1.02, 0.6, 1.51];
ub = [1.00, 1.65, 1.5, 4.00];

options = optimoptions('fmincon', ...
    'Algorithm', 'interior-point', ...
    'TolFun', 1e-10, ...
    'TolX', 1e-10, ...
    'TolCon', 1e-10, ...
    'MaxIterations', 1000, ...
    'Display', 'off', ...
    'OutputFcn', @(x,optimValues,state) ...
        OutFunLowerVsiEwmaXbarGamEAATS( ...
        x, optimValues, state, ...
        n, hS, deltamin, deltamax, tau0, a_shape, b_scale));

x = fmincon(@(x) ...
    ObjLowerVsiEwmaXbarGamEAATS(x, n, hS, deltamin, deltamax, a_shape, b_scale), ...
    x0, [], [], [], [], lb, ub, ...
    @(x) ConLowerVsiEwmaXbarGamSteady(x, n, hS, tau0, a_shape, b_scale), ...
    options);

lam = x(1);
hL  = x(2);
K1  = x(3);
K2  = x(4);

% Final performance
EAATS1 = EAATSFindLowerVsiEwmaXbarGam(n, deltamin, deltamax, hL, hS, lam, K1, K2, a_shape, b_scale) ; 

[AATS0, ~, ASI0] = TsLowerVsiEwmaXbarGamSteady(n, hL, hS, lam, K1, K2, 0, a_shape, b_scale);

fprintf(['lam = %6.4f  hL = %6.4f  K1 = %6.4f  K2 = %6.4f  ', ...
         'AATS0 = %6.2f  ASI0 = %6.2f EAATS1 = %6.2f \n'], ...
         lam, hL, K1, K2, AATS0, ASI0, EAATS1);
end
